### ISSUE TITLE
Authentication changes

### ISSUE THREAD

**Issue by CJS7070** [acm-uiuc/liquid#283]
As of today, CITES is no longer allowing LDAP/LDAPS binds to Active Directory (for authentication), such as how Liquid is currently running. Thus, we will need to change Liquid's auth to one of the following:

- Shibboleth
- ACM Crowd
- LDAP + GSSAPI/Kerberos and packet signing
- LDAP + TLS encryption (using STARTTLS/STOPTLS commands)

**Comment by colegleason** [comment]
For TLS, see https://pythonhosted.org/django-auth-ldap/authentication.html#notes.

If crowd isn't too bad, let's switch to that.

**Comment by ace-n** [comment]
++ to Crowd (since IIRC that's what Admin was transitioning to for other
services). The fewer configurations we have to maintain, the better.

This <https://bitbucket.org/sannies/django-crowd-backend/overview> and this
<https://djangosnippets.org/snippets/887/> might be useful resources. If we
prefer to roll our own and/or the first two links are outdated (in which
case, this
<http://stackoverflow.com/questions/25918873/send-soap-request-with-django>
 and this <https://developer.atlassian.com/display/CROWDDEV/SOAP+API> seem more
appropriate).

**Comment by colegleason** [comment]
I would look at https://github.com/gbezyuk/django-crowd first.

**Comment by ace-n** [comment]
:thumbsup: Good find.

**Comment by colegleason** [comment]
Working on this. Waiting on Crowd app from @CJS7070

**Comment by colegleason** [comment]
Note that this means no one can login to Intranet.

**Comment by adilmehmoodbutt** [comment]
How can i  migrate Gitlab accounts from standard accounts to ldap users along with work history.

**Comment by colegleason** [comment]
@adilmehmoodbutt: Sorry, but I think you have the wrong issue tracker. I
have no idea. Try contacting Gitlab support.

**Comment by CJS7070** [comment]
I have provided the application information to Cole; see him if you need it.
